USE MeLivro;

-- 
-- SELECT * FROM PRODUTO
--  WHERE PRODUTO.TIPO_PRODUTO = "Livro";

-- SELECT * FROM PRODUTO
-- WHERE PRODUTO.TIPO_PRODUTO = "Paper";
 
-- SELECT * FROM PRODUTO
--  WHERE PRODUTO.TIPO_PRODUTO = "Revista";

-- SELECT * FROM USUARIO
--  INNER JOIN VENDA
--  ON (USUARIO.CPF = VENDA.CPF);

 -- SELECT DISTINCT * FROM PAGAMENTO
--    INNER JOIN VENDA
  --  ON (PAGAMENTO.CODPAG = VENDA.CODPAG);

--  SELECT NOME,CPF,EMAIL,SENHA
--    FROM PESSOA;


-- Seleciona ordenando por código do pedido o nome da pessoa que solicitou o produto, o numero do seu cpf e o titulo deste produto
--    SELECT DISTINCT PEDIDO.CODPEDIDO,PESSOA.CPF,NOME,TITULO
--       FROM PEDIDO,PESSOA,PRODUTO
-- ORDER BY CODPEDIDO;     
  
--    SELECT DISTINCT CODPEDIDO,PEDIDO.CPF,TITULO,VALOR_VENDA
--       FROM PEDIDO,PRODUTO,VENDA
--       WHERE TIPO_PRODUTO = "Livro"
--       ORDER BY CODVENDA;
       
       
-- SELECT PESSOA.NOME,PESSOA.EMAIL,USUARIO.TELEFONE,USUARIO.CIDADE,USUARIO.ENDERECO FROM USUARIO
 --     INNER JOIN PESSOA ON PESSOA.CPF = USUARIO.CPF;      
       
       
 -- SELECT DISTINCT PESSOA.*, USUARIO.* FROM PESSOA CROSS JOIN USUARIO;
       
-- SELECT USUARIO.* FROM USUARIO
-- LEFT JOIN PESSOA ON PESSOA.CPF=USUARIO.CPF;  
                 

--SET SQL_SAFE_UPDATES=0;
--UPDATE PRODUTO 
 -- SET PRECO = '25.0' WHERE PRECO='35.50';
       

-- Mostra os dado inseridos nas tabelas 
-- SELECT *FROM PESSOA;
-- SELECT *FROM USUARIO;
-- SELECT *FROM PRODUTO;
-- SELECT *FROM LIVRO;
-- SELECT *FROM REVISTA;
-- SELECT *FROM PAPER;
-- SELECT *FROM ANUNCIO;
-- SELECT *FROM PEDIDO;
-- SELECT *FROM VENDA;
-- SELECT *FROM PRODUTO_PEDIDO;
-- SELECT *FROM VENDA_PEDIDO;
-- SELECT *FROM PAGAMENTO;
-- SELECT *FROM AVALIACAO;

