USE MeLivro;

-- 
-- SELECT * FROM PRODUTO
--  WHERE PRODUTO.TIPO_PRODUTO = "Livro";

-- SELECT * FROM PRODUTO
-- WHERE PRODUTO.TIPO_PRODUTO = "Paper";
 
-- SELECT * FROM PRODUTO
--  WHERE PRODUTO.TIPO_PRODUTO = "Revista";

-- SELECT * FROM USUARIO
  -- INNER JOIN VENDA
 -- ON (USUARIO.CPF = VENDA.CPF);

-- SELECT * FROM PAGAMENTO
--   INNER JOIN VENDA
 --   ON (PAGAMENTO.CODPAG = VENDA.CODPAG);


-- Mostra os dado inseridos nas tabelas 
-- SELECT *FROM PESSOA;
-- SELECT *FROM USUARIO;
-- SELECT *FROM PRODUTO;
-- SELECT *FROM LIVRO;
-- SELECT *FROM REVISTA;
-- SELECT *FROM PAPER;
-- SELECT *FROM ANUNCIO;
-- SELECT *FROM PEDIDO;
-- SELECT *FROM VENDA;
-- SELECT *FROM PRODUTO_PEDIDO;
-- SELECT *FROM VENDA_PEDIDO;
-- SELECT *FROM PAGAMENTO;
-- SELECT *FROM AVALIACAO;
